#! /usr/bin/env bash

dockerprep_ver='0.9'

# Used Tokens:
#  !@~DOCKERPREP_CMD~@!   Original Dockerprep command used to bootstrap a project
#  !@~DOCKERPREP_VER~@!   Current Dockerprep version
#  !@~SOURCE_IMAGE~@!     "SOURCE_IMAGE" argument

usage_short='''
Usage: dockerprep SOURCE_IMAGE[:TAG] REPO TAG [NAME]
'''

usage_long="$usage_short"'''
Arguments:
  SOURCE_IMAGE    Full name of a Docker repo to base project on
  :TAG            Optional (but highly recommended!) tag of SOURCE_IMAGE
  REPO            Repo/Image name (eg. electricwarr/dockerprep) for new project
  TAG             First version/tag of new project
  NAME            Optionally override using "REPO" as the Container name
'''

# Help and Version outputs
if [[ "$1" == '--help' ]]; then
  echo "$usage_long"
  exit 0
elif [[ "$1" == '--version' ]]; then
  echo "$dockerprep_ver"
  exit 0
fi

# Process parameters
if [[ $# -eq 4 ]]; then
  source_image="$1"
  repo="$2"
  tag="$3"
  name="$4"
  dockerprep_cmd="dockerprep $@"
elif [[ $# -eq 3 ]]; then
  # NAME <- REPO
  source_image="$1"
  repo="$2"
  tag="$3"
  name="$2"
  dockerprep_cmd="dockerprep $@"
else
  echo "$usage_short"
  exit 1
fi

templates_dir="$(dirname "$(realpath "$0")")/templates" # Resolves links

# -------
# Project
# -------

# Check for existing dockerprep project
if [ -f .dockerprep.cfg ]; then
  echo 'Warning: .dockerprep.cfg file found - please delete this file to run Dockerprep from scratch'
  exit 1
fi

cat << EOF > project.cfg
repo="$repo"
tag="$tag"
name="$name"

# NB:
#  - Command substitution can be used in variables here - try to use "\$(this format)" instead of \`backticks\` if possible
#  - Mount/Volume paths used here MUST be absolute - use eg. "\$(realpath SYMLINK_PATH)" if you don't want to hardcode them
EOF

# Dockerprep Config
cat "$templates_dir/.dockerprep.cfg" | sed -E "s/!@~DOCKERPREP_CMD~@!/${dockerprep_cmd//\//\\/}/g" | sed -E "s/!@~DOCKERPREP_VER~@!/${dockerprep_ver//\//\\/}/g" > .dockerprep.cfg || exit $?

# -----------------
# Dockerfile
# -----------------
# Read the existing Dockerfile template into memory, replace tokens, write out
cat "$templates_dir/Dockerfile" | sed -E "s/!@~SOURCE_IMAGE~@!/${source_image//\//\\/}/g" > Dockerfile || exit $?

# --------------
# Scripts
# --------------
for script in "$templates_dir"/*.sh; do
  cp "$script" . || exit $?
  if [ "$script" != "$templates_dir/build.sh" ]; then
    cat "$templates_dir"/cheat_sheet >> "$(basename "$script")" || exit $?
  fi
done
